feature: data api支持jwt透传
TencentBlueKing/bk-plugin-framework-python pull request #10
Opened 2022-04-27 09:21 UTC by wheel-w

2022-05-05 02:44 UTC, homholueng requested changes

2022-05-05 02:44 UTC, homholueng commented on bk-plugin-framework/bk_plugin_framework/envs.py
> +    user_token_key_name = "bk_ticket" if BKPAAS_ENVIRONMENT == "dev" else "jwt"
1. 默认应该使用 bk_token
2. 需要允许用户通过环境变量直接配置 user_token_key_name 的值

2022-05-05 02:44 UTC, homholueng commented on bk-plugin-framework/bk_plugin_framework/kit/api.py
> +from bkoauth import get_app_access_token
bkoauth这个包好像比较老了，需要确认 bkoauth 后续是否还会使用以及继续维护

2022-05-05 02:44 UTC, homholueng commented on bk-plugin-framework/bk_plugin_framework/kit/api.py
> +        if api_source is API_SOURCE.ESB and settings.BKPAAS_ENVIRONMENT != "dev":
插件的请求只会从 APIGW 来，不会走 ESB，这里理论上不需要支持 ESB 的来源（不存在）

2022-05-05 02:44 UTC, homholueng commented on bk-plugin-framework/bk_plugin_framework/services/bpf_service/middlewares.py
> +class TokenInjectMiddleware:
使用中间件是否有点覆盖范围过大？理论上只有 dispatch api 才需要处理 token 传递的逻辑

2022-05-05 03:35 UTC, wheel-w commented on bk-plugin-framework/bk_plugin_framework/envs.py
> +    user_token_key_name = "bk_ticket" if BKPAAS_ENVIRONMENT == "dev" else "jwt"
开发者设置USER_TOKEN_KEY_NAME环境变量的话，优先级高于user_token_key_name

2022-05-05 07:52 UTC, homholueng requested changes

2022-05-05 07:52 UTC, homholueng commented on bk-plugin-framework/bk_plugin_framework/constants.py
> +class ApiPlatform(Enum):
APIPlatform

2022-05-11 07:38 UTC, homholueng approved these changes

2022-05-11 07:38 UTC, merged