feature: template 支持可观侧性
TencentBlueKing/bk-plugin-framework-python pull request #42
Opened 2022-11-02 08:06 UTC by hanshuaikang

2022-11-15 02:41 UTC, tencentblueking-adm commented
[![CLA assistant check](https://bk-cla.bktencent.com:443/pull/badge/not_signed)](https://bk-cla.bktencent.com:443/TencentBlueKing/bk-plugin-framework-python?pullRequest=42) <br/>Thank you for your submission! We really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://bk-cla.bktencent.com:443/TencentBlueKing/bk-plugin-framework-python?pullRequest=42) before we can accept your contribution.<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://bk-cla.bktencent.com:443/check/TencentBlueKing/bk-plugin-framework-python?pullRequest=42) it.</sub>

2022-11-24 03:56 UTC, normal-wls requested changes

2022-11-24 03:56 UTC, normal-wls commented on template/{{cookiecutter.project_name}}/Procfile
> +{% if cookiecutter.enable_otel_metrics == "yes" -%}
注释忘了去掉？

2022-11-24 03:56 UTC, normal-wls commented on template/{{cookiecutter.project_name}}/Procfile
> +web: gunicorn bk_plugin_runtime.wsgi --timeout 120 -k gthread --threads 16 -w 1 --max-requests=1000
这里为何改成1

2024-11-19 12:54 UTC, closed without merging